//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherReportModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Weathers = new HashSet<Weather>();
        }
    
        public int cityId { get; set; }
        public string cityName { get; set; }
    
        public virtual ICollection<Weather> Weathers { get; set; }
    }
}
